packages:
  - 'apps/*'
  - 'packages/*'
  - 'services/*'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@tailwindcss/oxide'
  - bcrypt
  - esbuild
  - prisma
  - unrs-resolver
