export enum ErrorCode {
  API_ERROR = 'API_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  CONFLICT = 'CONFLICT',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  FOLDER_ALREADY_EXISTS = 'FOLDER_ALREADY_EXISTS',

  USER_EMAIL_ALREADY_IN_USE = 'USER_EMAIL_ALREADY_IN_USE',

  FOLDER_SLUG_EXISTS = 'FOLDER_SLUG_EXISTS',
}
